{% set version = "1.9.0" %}
{% set name = "simplejpeg" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5ac7d9489eeb812c2e7ea5c283994a29d9fefdfe5ed7b86c09d485e0dd366689

build:
  skip: true # [py<39]
  number: 0
  script:
    - cp ${RECIPE_DIR}/setup.py .  # [unix]
    - python -m pip install . --no-deps --ignore-installed --no-build-isolation -vv  # [unix]
    - copy %RECIPE_DIR%\setup.py . # [win]
    - python -m pip install . --no-deps --ignore-installed --no-build-isolation -vv  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - make         # [unix]
  host:
    - python
    - cython >=3.1.0,<3.2
    - pip
    - numpy {{ numpy }}
    - setuptools >=77.0.0
    - libjpeg-turbo {{ libjpeg_turbo }}
  run:
    - python
    - numpy

test:
  source_files:
    - test
  imports:
    - simplejpeg
  commands:
    - pip check
    - pytest -vvv
  requires:
    - pip
    - pytest
    - pillow

about:
  home: https://github.com/jfolz/simplejpeg
  summary: simplejpeg is a simple package based on recent versions of libturbojpeg for fast JPEG encoding and decoding.
  description: simplejpeg is a simple package based on recent versions of libturbojpeg for fast JPEG encoding and decoding.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/jfolz/simplejpeg
  doc_url: https://github.com/jfolz/simplejpeg/blob/master/README.rst

extra:
  recipe-maintainers:
    - carlodri