{% set name = "simplejpeg" %}
{% set version = "1.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5ac7d9489eeb812c2e7ea5c283994a29d9fefdfe5ed7b86c09d485e0dd366689

build:
  number: 0
  skip: true  # [py<39]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - nasm
  host:
    - python
    - pip
    - cython >=3.1.0,<4.0
    - numpy {{ numpy }}
    - setuptools >=77.0.0
    - jpeg {{ jpeg }}
  run:
    - python
    - numpy >=2.0.0

test:
  imports:
    - simplejpeg
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/jfolz/simplejpeg
  summary: Fast JPEG encoding and decoding via libjpeg-turbo
  description: |
    simplejpeg is a Python package based on libjpeg-turbo for fast JPEG encoding
    and decoding.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://github.com/jfolz/simplejpeg
  dev_url: https://github.com/jfolz/simplejpeg

extra:
  recipe-maintainers:
    - carlodri
